# Generated by Django 2.2.24 on 2021-10-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Запланировано', 'Запланировано'), ('Изменено', 'Изменено'), ('Отменено', 'Отмененно')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
